# Generated by Django 4.1.1 on 2022-09-17 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('e_mail', models.EmailField(max_length=150, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('id_users', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_article', models.CharField(max_length=255)),
                ('text_post', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_post', models.CharField(choices=[('news', 'Новости'), ('article', 'Статьи')], default='news', max_length=20)),
                ('sum_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribersUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bio_zoom.category')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bio_zoom.category')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bio_zoom.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='Bio_zoom.PostCategory', to='Bio_zoom.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='id_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bio_zoom.author'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum_rank', models.IntegerField(default=0)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bio_zoom.post')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='Bio_zoom.SubscribersUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
